workspace:
  base: /srv/app
  path: src/github.com/umschlag/umschlag-ui

pipeline:
  testing:
    image: webhippie/nodejs:latest
    pull: true
    commands:
      - npm install
      - npm run lint
      - npm run build
      - npm run test

  server:
    image: webhippie/golang:latest
    pull: true
    environment:
      CGO_ENABLED: 0
      TAGS:
      GOPATH: /srv/app
    commands:
      - make clean
      - make vet
      - make lint
      - make generate
      - make test
      - make build

  updater:
    image: webhippie/golang:latest
    pull: true
    environment:
      CGO_ENABLED: 0
      TAGS:
      GOPATH: /srv/app
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, release/*, refs/tags/* ]

  # coverage:
  #   image: plugins/coverage
  #   server: http://coverage.dronehippie.de
  #   when:
  #     event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: umschlag/umschlag-ui
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: umschlag/umschlag-ui
    tags: [ '${DRONE_BRANCH##release/v}' ]
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker
    repo: umschlag/umschlag-ui
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/umschlag-ui/${DRONE_TAG##v}
  #   recursive: true
  #   delete: true
  #   when:
  #     event: [ tag ]
  #     branch: [ refs/tags/* ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/umschlag-ui/${DRONE_TAG##release/v}
  #   recursive: true
  #   delete: true
  #   when:
  #     event: [ push ]
  #     branch: [ release/* ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/umschlag-ui/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: push
  #     branch: master

  github:
    image: plugins/github-release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  gitter:
    image: plugins/gitter
